name:                wordleSolver
version:             0.1.0.0
github:              "jennifererwangg/parallel_wordle"
license:             BSD3
author:              "Jennifer Wang"
maintainer:          "xw2763@columbia.edu"
copyright:           "2022 Jennifer Wang"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jennifererwangg/parallel_wordle>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- text
- deepseq
- parallel
- split
- monad-par
- parseargs

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  wordleSolver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2 # full optimization
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - wordleSolver

tests:
  wordleSolver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - wordleSolver
